version: "3.8"

services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    user: root
    ports:
      - "25565:25565"
      - "8123:8123"
    environment:
      EULA: "TRUE"
      MAX_MEMORY: "3G"
      INIT_MEMORY: "3G"
      TZ: "Europe/Samara"
      USE_AIKAR_FLAGS: true
      TYPE: "FABRIC"
      VERSION: "1.20.1"
      MOTD: "Дарова ёпта"
      DIFFICULTY: 'hard'
      ICON: "/custom/icon/asa.png"
      OVERRIDE_ICON: "TRUE"
      SNOOPER_ENABLED: false
      MODE: "survival"
      ALLOW_FLIGHT: "TRUE"
      SERVER_NAME: "Сервак ёпта"
      ONLINE_MODE: false
      COPY_MODS_SRC: '/custom/mods'
      COPY_PLUGINS_SRC: '/custom/plugins'
      COPY_PLUGINS_DEST: '/mods'
      COPY_CONFIG_SRC: '/custom/config'
      SYNC_SKIP_NEWER_IN_DESTINATION: true
      REMOVE_OLD_MODS: "TRUE"
    volumes:
    # Dynmap requires `chown -R 1000:1000 /data/minecraft/dynmap` or else it will not start
      - /data/minecraft/:/data
      - ./custom/:/custom
      - type: bind
        source: ./custom/dynmap/configuration.txt
        target: /data/dynmap/configuration.txt