version: '3.8'

services:
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft-server
    ports:
      - "25565:25565"   # Minecraft server port
      - "8123:8123"     # Dynmap or web interface port
    environment:
      EULA: "TRUE"
      MAX_MEMORY: "11G"
      INIT_MEMORY: "4G"
      TZ: "Europe/Samara"
      USE_AIKAR_FLAGS: "true"
      TYPE: "NEOFORGE"
      NEOFORGE_VERSION: "21.1.174"
      VERSION: "1.21.1"
      MOTD: "Дарова ёпта"
      DIFFICULTY: "hard"
      OVERRIDE_ICON: "TRUE"
      SNOOPER_ENABLED: "false"
      MODE: "survival"
      ALLOW_FLIGHT: "TRUE"
      SERVER_NAME: "Сервак ёпта"
      ONLINE_MODE: "false"
      COPY_MODS_SRC: "/custom/mods"
      COPY_CONFIG_SRC: "/custom/config"
      SYNC_SKIP_NEWER_IN_DESTINATION: "true"
      REMOVE_OLD_MODS: "TRUE"
      SIMULATION_DISTANCE: "7"
    volumes:
      - ./data/minecraft:/data
      - ./custom:/custom
    restart: unless-stopped
